import {
  MagnifyingGlass,
  FolderOpen,
  FloppyDisk,
  ClipboardText,
  Link,
  FileArrowUp,
  FileArrowDown,
  Code,
  TreeStructure,
  Table,
  TextAlignLeft,
  TextAlignJustify,
  SortAscending,
  ArrowsLeftRight,
  CheckSquare,
  FirstAid,
  Gear,
  Sun,
  Moon,
  SplitHorizontal,
  Plus,
  X as CloseIcon,
  ArrowCounterClockwise,
  ArrowClockwise,
} from '@phosphor-icons/react';

// Icon mapping helper for common actions
export const commandIcons = {
  openFile: <FolderOpen className="w-5 h-5" />,
  save: <FloppyDisk className="w-5 h-5" />,
  clipboard: <ClipboardText className="w-5 h-5" />,
  url: <Link className="w-5 h-5" />,
  importCsv: <FileArrowUp className="w-5 h-5" />,
  exportCsv: <FileArrowDown className="w-5 h-5" />,
  viewText: <Code className="w-5 h-5" />,
  viewTree: <TreeStructure className="w-5 h-5" />,
  viewTable: <Table className="w-5 h-5" />,
  format: <TextAlignLeft className="w-5 h-5" />,
  compact: <TextAlignJustify className="w-5 h-5" />,
  sort: <SortAscending className="w-5 h-5" />,
  compare: <ArrowsLeftRight className="w-5 h-5" />,
  validate: <CheckSquare className="w-5 h-5" />,
  repair: <FirstAid className="w-5 h-5" />,
  settings: <Gear className="w-5 h-5" />,
  themeLight: <Sun className="w-5 h-5" />,
  themeDark: <Moon className="w-5 h-5" />,
  split: <SplitHorizontal className="w-5 h-5" />,
  new: <Plus className="w-5 h-5" />,
  close: <CloseIcon className="w-5 h-5" />,
  undo: <ArrowCounterClockwise className="w-5 h-5" />,
  redo: <ArrowClockwise className="w-5 h-5" />,
  search: <MagnifyingGlass className="w-5 h-5" />,
};
